// Generated by scripts/11-write-dashboard-config.sh. Git-ignored.
// The anon key is safe in a browser: Row Level Security decides what it can read.
window.TESLA_MONITOR_CONFIG = {
  SUPABASE_URL: 'https://esppiwhzfxiunwrodgou.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzcHBpd2h6ZnhpdW53cm9kZ291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg2NTI1NjgsImV4cCI6MjEwNDIyODU2OH0.6xliYmHIxvOf83RZf8EuQKgHpz7mvKCUa-6AbQDFEs0',
};
